import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { ModalsContainer } from "@/components/modals/ModalsContainer";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { Header } from "@/src/features/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen max-h-screen overflow-hidden">
      <body className={cn(inter.className, "h-full")}>
        <Toaster />
        <ModalsContainer />
        <Header />
        {children}
      </body>
    </html>
  );
}
